import type { Metadata } from "next";
import "@fontsource-variable/comfortaa";
import "./globals.css";
import client from "@/utils/apolloClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-gray-400 bg-black`}>
       {children}
      </body>
    </html>
  );
}
